[project]
name = "mftd"
version = "0.1.0"
description = "Python Midi Fighter Twister configuration for Touch Designer"
readme = "README.md"
requires-python = "==3.11.1"
authors = [ { name = "Gary Tyler", email = "mail@garytyler.com" } ]
dependencies = []

[project.optional-dependencies]
dev = [
    "python-rtmidi>=1.5.8",
    "pytest>=6.2.5",
    "pytest-mock>=3.6.1",
    "inline-importer>=0.0.4",
    "black>=25.1.0",
    "mypy>=1.5.1",
    "isort[colors]>=5.9.3",
    "flake8>=7.0.0",
]

[project.scripts]
demo_main = "mftd.main:run"
version = "mftd.main:version"
inline = "mftd.inline:main"

[tool.mypy]
plugins = []
exclude = []

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
known_first_party = ["mftd"]
color_output = true
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,E701"
